# Generated by Django 5.1.4 on 2025-01-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('cpf_alunos', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nome_evento', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vagas', models.IntegerField()),
                ('data_evento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id_turma', models.IntegerField(primary_key=True, serialize=False)),
                ('modalidade', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('faixa_etaria', models.CharField(max_length=20)),
            ],
        ),
    ]
