# Generated by Django 5.1.3 on 2025-02-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='endereco',
        ),
        migrations.AddField(
            model_name='alunos',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='modalidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='rua',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='turmas',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
