# Generated by Django 5.1.4 on 2025-02-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_delete_admin_remove_alunos_endereco_alunos_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
