# Generated by Django 5.1.4 on 2025-02-05 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_alter_alunos_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagemAlunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7, unique=True)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='alunos',
            name='contagem_modalidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alunos',
            name='mes_inscricao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
