# Generated by Django 5.1.4 on 2025-02-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_contagemalunos_alunos_contagem_modalidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='contagem_modalidade',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='mes_inscricao',
        ),
    ]
