# Generated by Django 5.1.4 on 2025-02-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_user_delete_contagemalunos_evento_id_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='turmas',
        ),
    ]
