# Generated by Django 5.1.3 on 2025-02-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_alunos_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id_evento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
